### ISSUE TITLE
TTreeのreducedが未定義

### ISSUE THREAD

**Issue by mzks** [tomokiiga/PosTable#1]

**Comment by mzks** [comment]
TTree(またはTChain)のreducedがどこでも定義されていない.
fileを読み込んできて, treeという名前でデータを呼んでいるが,これは後半のreducedではない??

**Comment by tomokiiga** [comment]
reducedの定義をやり直して動かしましたが、やはりPosCenterの{}（初期化子リスト?）に対応してなさそうです。ひとつずつvectorでPosCenterX等にして定義するしかないのでしょうか。

**Comment by mzks** [comment]
残念ながら...
Keita Mizukoshi [水越 彗太]
Particle Physics Lab., Department of Physics, Kobe University
神戸大学 理学研究科 物理学専攻 粒子物理学研究室
e-mail: mzks@stu.kobe-u.ac.jp <mzks@ne.phys.sci.osaka-u.ac.jp>
